# Generated by Django 4.1.2 on 2022-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobadvert',
            old_name='company',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='experience_level',
            field=models.CharField(choices=[('ENTRY_LEVEL', 'Entry-level'), ('MID_LEVEL', 'Mid-level'), ('SENIOR', 'Senior')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='job_description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
