# Generated by Django 4.1.2 on 2022-10-24 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0002_rename_company_jobadvert_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='job_description',
            field=models.TextField(null=True),
        ),
    ]
