# Generated by Django 4.1.2 on 2022-10-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_jobadvert_owner_alter_jobadvert_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='published',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('CONTRACT', 'Contract'), ('REMOTE', 'Remote'), ('PART_TIME', 'Part-time')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('ENTRY_LEVEL', 'Entry-level'), ('MID_LEVEL', 'Mid-level'), ('SENIOR', 'Senior')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('linkedin_profile_url', models.URLField()),
                ('github_profile_url', models.URLField()),
                ('website', models.URLField()),
                ('years_of_experience', models.CharField(choices=[('1_', '0 - 1'), ('2_', '1 - 2'), ('3_', '3 - 4'), ('4_', '5 - 6'), ('5_', '7 and above')], max_length=30)),
                ('applicants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobadvert')),
            ],
        ),
    ]
